# **Tarea de Numpy**

Este notebook es el de los ejercicios >:)

In [2]:
!pip install numpy
import numpy as np

# Probando si si jala el numpy
my_arreglow = np.array([1, 2, 3, 4, 5])

print(my_arreglow)
print(np.mean(my_arreglow))



[notice] A new release of pip available: 22.3.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


[1 2 3 4 5]
3.0


## Ejercicios de refuerzo

### **Ejercicio 1 - Crear un array de ceros:**
Crea un array de tamaño (3, 4) lleno de ceros.

In [55]:
arrayZero = np.zeros([3,4])
print(arrayZero)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### **Ejercicio 2-  Suma de elementos:**
   Dado el array [1, 2, 3, 4, 5], calcula la suma de todos sus elementos usando NumPy.

In [56]:
array = np.array([1, 2, 3, 4, 5])
print(np.sum(array))


15


### **Ejercicio 3 - Encontrar el máximo y mínimo:**
Dado el array [10, 20, 30, 40, 50], encuentra el valor máximo y mínimo.

In [ ]:
array = np.array([10, 20, 30, 40, 50])

# Solución:)
print("Máximo:", np.max(array))
print("Mínimo:", np.min(array))


Máximo: 50
Mínimo: 10


### **Ejercicio 4 - Encontrar el máximo y mínimo:**
 Dado el array [10, 20, 30, 40, 50], encuentra el valor máximo y mínimo.


In [88]:
# Solución:)
array = np.array([10, 20, 30, 40, 50])

print("Minimo:", min(array))
print("Maximo:", max(array))


Minimo: 10
Maximo: 50


### **Ejercicio 5 - Generar números aleatorios:**
  Genera un array de 5 números aleatorios entre 0 y 1.

In [89]:
random_array = np.random.rand(5)
print(random_array)

[0.83273564 0.0225371  0.65461405 0.04812383 0.12038921]


### **Ejercicio 6 - Promedio de un array:**
Dado el array [5, 10, 15, 20, 25], calcula su promedio usando NumPy.

In [90]:
array = np.array([5, 10, 15, 20, 25])
print(np.mean(array))


15.0


### **Ejercicio 7 - Concatenar dos arrays**
Dados los arrays A = [1, 2, 3] y B = [4, 5, 6], concaténalos en un solo array.

In [91]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
C = np.concatenate((A, B))
print(C)


[1 2 3 4 5 6]


### **Ejercicio 8 - Reshape de un Array**
Dado el array [1, 2, 3, 4, 5, 6], cámbialo a una matriz de 2x3.

In [92]:
array = np.array([1, 2, 3, 4, 5, 6])
reshaped = array.reshape((2, 3))
print(reshaped)


[[1 2 3]
 [4 5 6]]


### **Ejercicio 9 - Producto punto (dot product):**
Dados dos arrays A = [1, 2, 3] y B = [4, 5, 6], calcula su producto punto

In [93]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
producto_punto = np.dot(A, B)
print(producto_punto)


32


### **Ejercicio 10 - Reorganizar un array:**
Dado el array [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], conviértelo en una matriz (2, 5).

In [94]:
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
reorganizado = array.reshape((2, 5))
print(reorganizado)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


### **Ejercicio extra - Encontrar el *k*-ésimo elemento más pequeño en un array**
Dado arr = np.array([9, 3, 6, 2, 1, 7]), encuentra el 3er elemento más pequeño sin ordenar el array completo.

**Pista solución 1**: Se puede hacer con un método de Numpy

**Pista solución 2**: El código se hace más complicado, pero se puede resolver con ciclos iterativos.

In [109]:
#Solucion :o
arr = np.array([9, 3, 6, 2, 1, 7])

encontrado = np.partition(arr, 2)[2]
print("k-ésimo encontrado:", encontrado)

k-ésimo encontrado: 3


## **Ejercicios aplicados**

### **Ejercicio: Cálculo de ROI (Retorno de Inversión)**
Dadas las inversiones ([1000, 1500, 2000]) y sus retornos ([1200, 1650, 1800]), calcula el ROI porcentual para cada caso.

*(Fórmula: ROI = (retorno - inversión) / inversión * 100)*

In [110]:
inversiones = np.array([1000, 1500, 2000])
retornos = np.array([1200, 1650, 1800])
roi = (retornos - inversiones) / inversiones * 100
print("ROI (%):", roi)


ROI (%): [ 20.  10. -10.]


### **Ejercicio: Normalización de Datos**
Tienes un dataset de precios de productos (en USD): [250, 320, 150, 500, 210]. Normaliza los valores al rango [0, 1] para compararlos en una escala común.

**Formulita de la normalización**: (x - min) / (max - min): Para una escala valores entre 0 y 1.

In [111]:
precios = np.array([250, 320, 150, 500, 210])
normalizados = (precios - np.min(precios)) / (np.max(precios) - np.min(precios))
print(normalizados)


[0.28571429 0.48571429 0.         1.         0.17142857]


### **Ejercicio: Filtrado de Datos**
En un array de ventas diarias ([1200, 0, 750, 2400, 0, 1800]), reemplaza los ceros (días sin ventas) por el promedio de los días con ventas.

In [112]:
ventas = np.array([1200, 0, 750, 2400, 0, 1800])
promedio_ventas = np.mean(ventas[ventas > 0])
ventas_filtradas = np.where(ventas == 0, promedio_ventas, ventas)
print(ventas_filtradas)


[1200.  1537.5  750.  2400.  1537.5 1800. ]


### **Ejercicio - Análisis de Presión Arterial**
Tenemos un dataset de mediciones de presión arterial sistólica (mmHg) de 10 pacientes:
[120, 135, 140, 118, 150, 130, 160, 125, 142, 128].

Calculen:
- Media y desviación estándar.
- Identifiquen valores fuera del rango normal (90–140 mmHg).

In [113]:
presion = np.array([120, 135, 140, 118, 150, 130, 160, 125, 142, 128])
media = np.mean(presion)
desviacion = np.std(presion)
fuera_rango = presion[(presion < 90) | (presion > 140)]
print("Media:", media)
print("Desviación estándar:", desviacion)
print("Valores fuera del rango:", fuera_rango)


Media: 134.8
Desviación estándar: 12.69488085804668
Valores fuera del rango: [150 160 142]


### **Ejercicio - Cálculo del PIB per Cápita**
Dados el PIB (en millones de USD) [500, 320, 700, 450] y la población (en millones) [10, 8, 12, 9] de 4 países, calculen el PIB per cápita y determinen el país con el mayor valor.

In [114]:
pib = np.array([500, 320, 700, 450])
poblacion = np.array([10, 8, 12, 9])
pib_per_capita = pib / poblacion
indice_max = np.argmax(pib_per_capita)
print("PIB per cápita:", pib_per_capita)
print("País con mayor PIB per cápita:", indice_max)

PIB per cápita: [50.         40.         58.33333333 50.        ]
País con mayor PIB per cápita: 2


### **Ejercicio - Sistema de Drops (Probabilidades)**
En un videojuego RPG, los enemigos al ser vencidos, pueden dropear (soltar):
- 0 = Nada (50%).
- 1 = Poción (30%).
- 2 = Arma (15%).
- 3 = Artefacto (5%).

Simula 100 drops y cuenta cuántos artefactos se obtuvieron.

*Ejemplo de salida*:

```
Artifactos obtenidos: 3
```



In [115]:
drops = np.random.choice([0, 1, 2, 3], size=100, p=[0.5, 0.3, 0.15, 0.05])
artefactos = np.count_nonzero(drops == 3)
print("Artefactos obtenidos:", artefactos)

Artefactos obtenidos: 4
